#!/bin/bash
echo "📧 PREPARING TO EMAIL PROTECTION DOCUMENTS"
echo "=========================================="

# Create a zip file of all protection documents
tar -czf substrate_x_protection_package.tar.gz *.txt *.tex *.sh ../*.py

echo "Package created: substrate_x_protection_package.tar.gz"
echo ""
echo "📋 MANUAL EMAIL INSTRUCTIONS:"
echo ""
echo "1. OPEN YOUR EMAIL CLIENT (Gmail recommended)"
echo "2. COMPOSE NEW EMAIL"
echo "3. TO: briankenda99@gmail.com, foreignstash003@gmail.com"
echo "4. SUBJECT: Substrate X Theory - Legal Protection - $(date +"%Y-%m-%d")"
echo "5. BODY: Copy and paste the text below"
echo ""
echo "=== EMAIL BODY TEXT ==="
echo ""
echo "SUBSTRATE X THEORY - LEGAL PROTECTION DOCUMENTS"
echo "Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo ""
echo "This email serves as timestamped proof of my intellectual property"
echo "claim for Substrate X Theory, developed by Mwirigi Bryan Kenda"
echo "(DOB: 26 September 2003, Kenyan citizen)."
echo ""
echo "The attached protection package contains:"
echo "- Legal priority claims"
echo "- Academic credentials" 
echo "- Theory documentation"
echo "- Validation test results"
echo "- arXiv submission preparation"
echo ""
echo "This work represents independent research conducted outside"
echo "university coursework and without university resources."
echo ""
echo "Contact: briankenda99@gmail.com / +254768575932"
echo ""
echo "=== END EMAIL BODY ==="
echo ""
echo "6. ATTACH: substrate_x_protection_package.tar.gz"
echo "7. SEND TO BOTH YOUR EMAIL ADDRESSES"
echo ""
echo "🚀 AFTER SENDING:"
echo "   - DO NOT DELETE the sent emails"
echo "   - They serve as legal timestamp evidence"
echo "   - Keep them in your 'Sent' folder permanently"
